# Generated by Django 3.1.4 on 2021-01-02 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='url',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
