# Generated by Django 3.1.4 on 2021-01-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0002_encryptedfile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
