# Generated by Django 3.1.4 on 2021-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0003_auto_20210102_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
