# Generated by Django 3.1.4 on 2021-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0004_auto_20210102_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='key',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
