# Generated by Django 3.1.4 on 2021-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0006_auto_20210103_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=50)),
                ('file', models.FileField(upload_to=':\\Users\\ASUS\\Desktop\\Projects\\Projects\\converter\\static/media/')),
                ('key', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='encryptedfile',
            old_name='filename',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to=':\\Users\\ASUS\\Desktop\\Projects\\Projects\\converter\\static/media/'),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='useremail',
            field=models.EmailField(max_length=40),
        ),
    ]
