# Generated by Django 3.2 on 2021-04-22 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0007_auto_20210221_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='path',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='useremail',
        ),
        migrations.AddField(
            model_name='decryptedfile',
            name='encrypted_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='mnt/c/Users/ASUS/Desktop/Projects And Development/Projects/converter/static/media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='encrypted_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='mnt/c/Users/ASUS/Desktop/Projects And Development/Projects/converter/static/media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='username',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
