# Generated by Django 3.2 on 2021-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0008_auto_20210422_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
