# Generated by Django 3.2 on 2021-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0010_auto_20210422_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='key',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
