# Generated by Django 3.2 on 2021-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptfiles', '0012_delete_decryptedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='username',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
